from datetime import datetime
from unittest import TestCase
from financas_automatizadas.nubank import filter_account_transactions
from freezegun import freeze_time


class AccountTest(TestCase):
    def test_get_account_feed_events(self):
        # Arrange
        account_statements_paginated = {
            "pageInfo": {"hasNextPage": True},
            "edges": [
                # Pagamendo agendado
                {
                    "cursor": "ezpwcmlvcml0eSAwLCA6dGltZXN0YW1wICNudS90aW1lICIyMDIzLTAyLTA4VDEyOjAwOjAwWiIsIDppZCAjdXVpZCAiNjNiNDNjYWQtYzQ0YS00ZTc1LWFhNzYtNjA1NTUwZDBmNjA4In0=",
                    "node": {
                        "tags": ["money-out", "payments"],
                        "showClock": False,
                        "displayDate": "08 FEV",
                        "footer": "R$\xa01.248,73",
                        "title": "Pagamento agendado",
                        "detailsDeeplink": "nuapp://flutter/savings/details-screen/type/BARCODE_PAYMENT/id/63b43cad-c44a-4e75-aa76-605550d0f608",
                        "id": "63b43cad-c44a-4e75-aa76-605550d0f608",
                        "strikethrough": False,
                        "kind": "NEUTRAL",
                        "iconKey": "nuds_v2_icon.calendar_scheduled",
                        "postDate": "2023-02-08",
                        "detail": "Imposto de casa ",
                        "amount": 1248.73,
                    },
                },
                # Pix agendado
                {
                    "cursor": "ezpwcmlvcml0eSAwLCA6dGltZXN0YW1wICNudS90aW1lICIyMDIzLTAxLTEyVDAzOjAwOjAwWiIsIDppZCAjdXVpZCAiNjNiMzVlMTEtNTVlYy00ZDBkLWIwZmEtNWI1NWMyYmFlMTJmIn0=",
                    "node": {
                        "tags": ["money-out"],
                        "showClock": False,
                        "displayDate": "12 JAN",
                        "footer": "Pix",
                        "title": "Transferência agendada",
                        "detailsDeeplink": "nuapp://flutter/savings/details-screen/type/PIX_TRANSFER_OUT_REQUEST/id/63b35e11-55ec-4d0d-b0fa-5b55c2bae12f",
                        "id": "63b35e11-55ec-4d0d-b0fa-5b55c2bae12f",
                        "strikethrough": False,
                        "kind": "NEUTRAL",
                        "iconKey": "nuds_v2_icon.clock",
                        "postDate": "2023-01-12",
                        "detail": "Magrela \nR$\xa0250,00",
                        "amount": 250.0,
                    },
                },
                # Pix enviado
                {
                    "cursor": "ezpwcmlvcml0eSAwLCA6dGltZXN0YW1wICNudS90aW1lICIyMDIzLTAxLTA3VDEyOjUxOjI3LjY2NFoiLCA6aWQgI3V1aWQgIjYzYjk2YWNlLWQ5MTQtNDgyZC04ZDZlLTZjYmEyYjRkMTI4NyJ9",
                    "node": {
                        "tags": ["money-out"],
                        "showClock": False,
                        "displayDate": "Ontem",
                        "footer": "Pix",
                        "title": "Transferência enviada",
                        "detailsDeeplink": "nuapp://flutter/savings/details-screen/type/PIX_TRANSFER_OUT_REQUEST/id/63b96ace-d914-482d-8d6e-6cba2b4d1287",
                        "id": "63b96ace-d914-482d-8d6e-6cba2b4d1287",
                        "strikethrough": False,
                        "kind": "NEUTRAL",
                        "iconKey": "nuds_v2_icon.money_out",
                        "postDate": "2023-01-07",
                        "detail": "Joãozinho \nR$\xa015,00",
                        "amount": 15.0,
                    },
                },
                # Boleto pago
                {
                    "cursor": "ezpwcmlvcml0eSAwLCA6dGltZXN0YW1wICNudS90aW1lICIyMDIzLTAxLTA1VDEzOjM5OjM2Ljk4MloiLCA6aWQgI3V1aWQgIjYzYTYzNDRjLTZmMTYtNDYxOS04ZmYwLTg2ZGQ5N2ZiOWQwMyJ9",
                    "node": {
                        "tags": ["money-out", "payments"],
                        "showClock": False,
                        "displayDate": "05 JAN",
                        "footer": "R$\xa0137,93",
                        "title": "Pagamento efetuado",
                        "detailsDeeplink": "nuapp://flutter/savings/details-screen/type/BARCODE_PAYMENT/id/63a6344c-6f16-4619-8ff0-86dd97fb9d03",
                        "id": "63a6344c-6f16-4619-8ff0-86dd97fb9d03",
                        "strikethrough": False,
                        "kind": "NEUTRAL",
                        "iconKey": "nuds_v2_icon.bar_code",
                        "postDate": "2023-01-05",
                        "detail": "Internet SA",
                        "amount": 137.93,
                    },
                },
                # Aplicação em fundo
                {
                    "cursor": "ezpwcmlvcml0eSAwLCA6dGltZXN0YW1wICNudS90aW1lICIyMDIzLTAxLTAzVDE0OjM0OjM4LjU1OFoiLCA6aWQgI3V1aWQgIjYyMDZmYzliLTRjNjktMzQ1Yy1hY2JkLWExMTUyOTIzYzllYyJ9",
                    "node": {
                        "tags": None,
                        "showClock": False,
                        "displayDate": "03 JAN",
                        "footer": "R$ 10.000,00",
                        "title": "Aplicação fundo",
                        "detailsDeeplink": None,
                        "id": "6206fc9b-4c69-345c-acbd-a1152923c9ec",
                        "strikethrough": False,
                        "kind": "NEUTRAL",
                        "iconKey": "nuds_v2_icon.money_out",
                        "postDate": "2023-01-03",
                        "detail": "Nu Reserva Imediata",
                        "amount": 1000.0,
                    },
                },
                # Aplicação RDB
                {
                    "cursor": "ezpwcmlvcml0eSAwLCA6dGltZXN0YW1wICNudS90aW1lICIyMDIzLTAxLTAzVDE0OjM0OjE0LjA4NFoiLCA6aWQgI3V1aWQgImJiZWI5MGQzLWIzNDktM2Q5NC1hOWQ0LTM0ZGRkZDc3OTZmMSJ9",
                    "node": {
                        "tags": None,
                        "showClock": False,
                        "displayDate": "03 JAN",
                        "footer": "R$ 40.000,00",
                        "title": "Aplicação RDB",
                        "detailsDeeplink": None,
                        "id": "bbeb90d3-b349-3d94-a9d4-34dddd7796f1",
                        "strikethrough": False,
                        "kind": "NEUTRAL",
                        "iconKey": "nuds_v2_icon.money_out",
                        "postDate": "2023-01-03",
                        "detail": "RDB Resgate Imediato",
                        "amount": 4000.0,
                    },
                },
                # Pix Recebido => kind positive icon money_in
                {
                    "cursor": "ezpwcmlvcml0eSAwLCA6dGltZXN0YW1wICNudS90aW1lICIyMDIzLTAxLTAzVDE0OjA4OjA0LjQ4NloiLCA6aWQgI3V1aWQgIjYzYjQzNmM0LTlkNjQtNGQxMy04NGQ4LWNlMTM2N2U2ZGRlNiJ9",
                    "node": {
                        "tags": ["money-in"],
                        "showClock": False,
                        "displayDate": "03 JAN",
                        "footer": None,
                        "title": "Transferência recebida",
                        "detailsDeeplink": "nuapp://flutter/savings/details-screen/type/TRANSFER_IN/id/63b436c4-9d64-4d13-84d8-ce1367e6dde6",
                        "id": "63b436c4-9d64-4d13-84d8-ce1367e6dde6",
                        "strikethrough": False,
                        "kind": "POSITIVE",
                        "iconKey": "nuds_v2_icon.money_in",
                        "postDate": "2023-01-03",
                        "detail": "EMPRESA LTDA\nR$\xa012.345,00",
                        "amount": 12345.0,
                    },
                },
                # Falha no pagamento strikethrough True
                {
                    "cursor": "ezpwcmlvcml0eSAwLCA6dGltZXN0YW1wICNudS90aW1lICIyMDIzLTAxLTAzVDA0OjQ5OjM5LjM3NVoiLCA6aWQgI3V1aWQgIjYzOGEyNGY3LTNiYTQtNDMxMi05ZTAxLTcxNmQ0ODYxNWY5MiJ9",
                    "node": {
                        "tags": ["money-out", "payments"],
                        "showClock": False,
                        "displayDate": "03 JAN",
                        "footer": "R$\xa04.028,50",
                        "title": "Falha no agendamento",
                        "detailsDeeplink": None,
                        "id": "638a24f7-3ba4-4312-9e01-716d48615f92",
                        "strikethrough": True,
                        "kind": "NEUTRAL",
                        "iconKey": "nuds_v2_icon.bar_code",
                        "postDate": "2023-01-03",
                        "detail": "NAO INFORMADO",
                        "amount": 4028.5,
                    },
                },
                #  Outro Pix enviado, mas sem Pix no footer
                {
                    "cursor": "ezpwcmlvcml0eSAwLCA6dGltZXN0YW1wICNudS90aW1lICIyMDIzLTAxLTAyVDIyOjQxOjAwLjUwN1oiLCA6aWQgI3V1aWQgIjYzYjM1ZDdjLTYwNDUtNGZmNC04ZGIxLWFkYTc4ZGIzMGUzMyJ9",
                    "node": {
                        "tags": ["money-out"],
                        "showClock": False,
                        "displayDate": "02 JAN",
                        "footer": None,
                        "title": "Transferência enviada",
                        "detailsDeeplink": "nuapp://flutter/savings/details-screen/type/PIX_TRANSFER_OUT_REQUEST/id/63b35d7c-6045-4ff4-8db1-ada78db30e33",
                        "id": "63b35d7c-6045-4ff4-8db1-ada78db30e33",
                        "strikethrough": False,
                        "kind": "NEUTRAL",
                        "iconKey": "nuds_v2_icon.money_out",
                        "postDate": "2023-01-02",
                        "detail": "Vitoria Nardin de Paula\nR$\xa0739,50",
                        "amount": 739.5,
                    },
                },
                # Pagamento da fatura
                {
                    "cursor": "ezpwcmlvcml0eSAwLCA6dGltZXN0YW1wICNudS90aW1lICIyMDIzLTAxLTAxVDIzOjQ0OjU5LjU1NVoiLCA6aWQgI3V1aWQgIjYzYjIxYWZiLTdjNjQtNDU5YS1iM2I1LTU3MDVhYWQ3Y2I1YiJ9",
                    "node": {
                        "tags": ["money-out", "payments"],
                        "showClock": False,
                        "displayDate": "01 JAN",
                        "footer": None,
                        "title": "Pagamento da fatura",
                        "detailsDeeplink": "nuapp://flutter/savings/details-screen/type/CREDIT_CARD_BILL_PAYMENT/id/63b21afb-7c64-459a-b3b5-5705aad7cb5b",
                        "id": "63b21afb-7c64-459a-b3b5-5705aad7cb5b",
                        "strikethrough": False,
                        "kind": "NEUTRAL",
                        "iconKey": "nuds_v2_icon.card",
                        "postDate": "2023-01-01",
                        "detail": "R$\xa01.545,35",
                        "amount": 1545.35,
                    },
                },
                # Resgate RDB
                {
                    "cursor": "ezpwcmlvcml0eSAwLCA6dGltZXN0YW1wICNudS90aW1lICIyMDIyLTEyLTMxVDE3OjM1OjMxLjM2NFoiLCA6aWQgI3V1aWQgIjA3YzhkNjBkLTJkNTItMzY3NC1hYzZlLWY3ZjdiNTQzZDk1NyJ9",
                    "node": {
                        "tags": None,
                        "showClock": False,
                        "displayDate": "31 DEZ 2022",
                        "footer": "R$ 23.000,00",
                        "title": "Resgate RDB",
                        "detailsDeeplink": None,
                        "id": "07c8d60d-2d52-3674-ac6e-f7f7b543d957",
                        "strikethrough": False,
                        "kind": "NEUTRAL",
                        "iconKey": "nuds_v2_icon.money_in",
                        "postDate": "2022-12-31",
                        "detail": "RDB Resgate Imediato",
                        "amount": 2300.0,
                    },
                },
            ],
        }

        expected_transactions = [
            {
                "amount": 15.0,
                "detail": "Joãozinho \nR$\xa015,00",
                "detailsDeeplink": "nuapp://flutter/savings/details-screen/type/PIX_TRANSFER_OUT_REQUEST/id/63b96ace-d914-482d-8d6e-6cba2b4d1287",
                "displayDate": "Ontem",
                "footer": "Pix",
                "iconKey": "nuds_v2_icon.money_out",
                "id": "63b96ace-d914-482d-8d6e-6cba2b4d1287",
                "kind": "NEUTRAL",
                "postDate": "2023-01-07",
                "showClock": False,
                "strikethrough": False,
                "tags": ["money-out"],
                "title": "Transferência enviada",
            },
            {
                "amount": 137.93,
                "detail": "Internet SA",
                "detailsDeeplink": "nuapp://flutter/savings/details-screen/type/BARCODE_PAYMENT/id/63a6344c-6f16-4619-8ff0-86dd97fb9d03",
                "displayDate": "05 JAN",
                "footer": "R$\xa0137,93",
                "iconKey": "nuds_v2_icon.bar_code",
                "id": "63a6344c-6f16-4619-8ff0-86dd97fb9d03",
                "kind": "NEUTRAL",
                "postDate": "2023-01-05",
                "showClock": False,
                "strikethrough": False,
                "tags": ["money-out", "payments"],
                "title": "Pagamento efetuado",
            },
            {
                "amount": 1000.0,
                "detail": "Nu Reserva Imediata",
                "detailsDeeplink": None,
                "displayDate": "03 JAN",
                "footer": "R$ 10.000,00",
                "iconKey": "nuds_v2_icon.money_out",
                "id": "6206fc9b-4c69-345c-acbd-a1152923c9ec",
                "kind": "NEUTRAL",
                "postDate": "2023-01-03",
                "showClock": False,
                "strikethrough": False,
                "tags": None,
                "title": "Aplicação fundo",
            },
            {
                "amount": 4000.0,
                "detail": "RDB Resgate Imediato",
                "detailsDeeplink": None,
                "displayDate": "03 JAN",
                "footer": "R$ 40.000,00",
                "iconKey": "nuds_v2_icon.money_out",
                "id": "bbeb90d3-b349-3d94-a9d4-34dddd7796f1",
                "kind": "NEUTRAL",
                "postDate": "2023-01-03",
                "showClock": False,
                "strikethrough": False,
                "tags": None,
                "title": "Aplicação RDB",
            },
            {
                "amount": 12345.0,
                "detail": "EMPRESA LTDA\nR$\xa012.345,00",
                "detailsDeeplink": "nuapp://flutter/savings/details-screen/type/TRANSFER_IN/id/63b436c4-9d64-4d13-84d8-ce1367e6dde6",
                "displayDate": "03 JAN",
                "footer": None,
                "iconKey": "nuds_v2_icon.money_in",
                "id": "63b436c4-9d64-4d13-84d8-ce1367e6dde6",
                "kind": "POSITIVE",
                "postDate": "2023-01-03",
                "showClock": False,
                "strikethrough": False,
                "tags": ["money-in"],
                "title": "Transferência recebida",
            },
            {
                "amount": 739.5,
                "detail": "Vitoria Nardin de Paula\nR$\xa0739,50",
                "detailsDeeplink": "nuapp://flutter/savings/details-screen/type/PIX_TRANSFER_OUT_REQUEST/id/63b35d7c-6045-4ff4-8db1-ada78db30e33",
                "displayDate": "02 JAN",
                "footer": None,
                "iconKey": "nuds_v2_icon.money_out",
                "id": "63b35d7c-6045-4ff4-8db1-ada78db30e33",
                "kind": "NEUTRAL",
                "postDate": "2023-01-02",
                "showClock": False,
                "strikethrough": False,
                "tags": ["money-out"],
                "title": "Transferência enviada",
            },
            {
                "amount": 1545.35,
                "detail": "R$\xa01.545,35",
                "detailsDeeplink": "nuapp://flutter/savings/details-screen/type/CREDIT_CARD_BILL_PAYMENT/id/63b21afb-7c64-459a-b3b5-5705aad7cb5b",
                "displayDate": "01 JAN",
                "footer": None,
                "iconKey": "nuds_v2_icon.card",
                "id": "63b21afb-7c64-459a-b3b5-5705aad7cb5b",
                "kind": "NEUTRAL",
                "postDate": "2023-01-01",
                "showClock": False,
                "strikethrough": False,
                "tags": ["money-out", "payments"],
                "title": "Pagamento da fatura",
            },
            {
                "amount": 2300.0,
                "detail": "RDB Resgate Imediato",
                "detailsDeeplink": None,
                "displayDate": "31 DEZ 2022",
                "footer": "R$ 23.000,00",
                "iconKey": "nuds_v2_icon.money_in",
                "id": "07c8d60d-2d52-3674-ac6e-f7f7b543d957",
                "kind": "NEUTRAL",
                "postDate": "2022-12-31",
                "showClock": False,
                "strikethrough": False,
                "tags": None,
                "title": "Resgate RDB",
            },
        ]

        # Act
        filtered_transactions = filter_account_transactions(
            account_statements=account_statements_paginated
        )

        # Assert
        self.assertEqual(len(expected_transactions), len(filtered_transactions))
        self.assertEqual(expected_transactions, filtered_transactions)
