name: Sync transactions from Nubank and Itaú to my YNAB(You Need A Budget) every day at 6AM
on:
  schedule:
    - cron: 0 6 * * *  # Every day at 6AM
  push:
      branches:
        - trunk
jobs:
  sync:
    env:
      YNAB_TOKEN: ${{ secrets.YNAB_TOKEN }}
      YNAB_BUDGET_ID: ${{ secrets.YNAB_BUDGET_ID }}
      PLUGGY_CLIENT_ID: ${{ secrets.PLUGGY_CLIENT_ID }}
      PLUGGY_CLIENT_SECRET: ${{ secrets.PLUGGY_CLIENT_SECRET }}
      ACCOUNT_PAIRS: ${{ secrets.ACCOUNT_PAIRS }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"
          enable-cache: true
      - run: uv --version
      - name: Install Python 3.12
        run: uv python install 3.12
      - run: uv run python --version
      - name: Verify cache
        if: steps.setup-uv.outputs.cache-hit == 'true'
        run: echo "Cache was restored"
      - name: Run sync to ynab
        run: |
          uv run python financas_automatizadas/main.py
